### PR TITLE
Add support for NSFastEnumeration 

### PR DESCRIPTION
**Pull request by keithwahn**
This fixes issue #1.  Please scrutinize.  I got the idea form [CueSyncArray](https://github.com/Cue/TheKitchenSync/blob/master/Classes/Collections/CueSyncArray.mm)

### CODE REVIEW

**Comment by levigroker** [comment]
Thanks @keithwahn! I'll take a look.

**Comment by keithwahn** [comment]
Do not merge!  Basically the `for` `in` loop works, but the objects inside are invalid.  Going to see if there's a way to make this work.

**Comment by levigroker** [comment]
Thanks Keith. I looked at this a bit yesterday and had reservations. The array copy won't retain the array objects outside the call, so the copied objects will be autoreleased. I have other concerns about the concurrency of this approach as well.

Here's some resources I was looking at:

http://nshipster.com/enumerators/
https://www.bignerdranch.com/blog/fast-enumeration-part-2/
https://www.mikeash.com/pyblog/friday-qa-2010-04-16-implementing-fast-enumeration.html

**Comment by keithwahn** [comment]
Well I've learned a lot along the way, but unfortunately I have to move on to another solution for the time being.  Hopefully I can revisit this in the future.

During my testing is seems that `countByEnumeratingWithState` is called twice during the for each loop, once in the beginning, and once in the end, when the return value is zero.  The first time through `state->state = 0` and the 2nd time `state->state = -1`.  

Potentially that could be used to retain and release a NSArray copy property that is retained by the class.  But that would have the caveat that only one `for each` loop could run at a time, and would have to be protected as such.

```
@property (nonatomic,strong) NSMutableArray *encapsulatedArrayCopy;
```

Or, perhaps it's possible to write a completely custom  `countByEnumeratingWithState`, as shown in the [Mike Ash article](https://www.mikeash.com/pyblog/friday-qa-2010-04-16-implementing-fast-enumeration.html).

**Comment by levigroker** [comment]
Thanks for the effort. If you find a solution please let me know.

**Pull request closed without merging**
